name: Simple Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print message
        run: echo "Hello Maryam! 🎉 Your workflow is running correctly!"
